name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    # - name: Setup Node
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '10.x'
    - run: npm ci
    - run: npm run docs:build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
